version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile.api
        ports:
         - "5000:5000"

    gather:
        build:
            context: .
            dockerfile: Dockerfile.gather